2020-02-02 16:49:32,282 : INFO : Machine : Mission Pinball Framework Core Engine v0.54.0-dev.2
2020-02-02 16:49:32,282 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': '/usr/local/lib/python3.6/dist-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2020-02-02-16-49-32-mpf-pinball.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-02-02 16:49:32,282 : INFO : Machine : MPF path: /usr/local/lib/python3.6/dist-packages/mpf
2020-02-02 16:49:32,282 : INFO : Machine : Machine path: /home/me/stripFeb2/monitor
2020-02-02 16:49:32,282 : INFO : Machine : Platform: linux
2020-02-02 16:49:32,282 : INFO : Machine : Python executable location: /usr/bin/python3
2020-02-02 16:49:32,282 : INFO : Machine : Python version: 3.6.9 (64-bit)
2020-02-02 16:49:32,282 : INFO : Machine : Machine config file #1: config.yaml
2020-02-02 16:49:32,283 : WARNING : ConfigProcessor : Cache file not found: /tmp/501586142d54844e7842d1be7c11c94e.mpf_cache
2020-02-02 16:49:32,283 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.6/dist-packages/mpf/mpfconfig.yaml.
2020-02-02 16:49:32,338 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.6/dist-packages/mpf/mpfconfig.yaml
2020-02-02 16:49:32,344 : INFO : ConfigProcessor : Loading config from file /home/me/stripFeb2/monitor/config/config.yaml.
2020-02-02 16:49:32,344 : ERROR : root : Could not find file /home/me/stripFeb2/monitor/config/config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/file_manager.py", line 79, in load
    file = FileManager.locate_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/file_manager.py", line 53, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: /home/me/stripFeb2/monitor/config/config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mpf/commands/game.py", line 226, in __init__
    self.machine = MachineController(mpf_path, machine_path, vars(self.args))
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/machine.py", line 199, in __init__
    self._load_config()
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/machine.py", line 431, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/file_manager.py", line 82, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file /home/me/stripFeb2/monitor/config/config.yaml
